

# set up conditions for testing
# Restart R: Ctrl-Shift-F10
rm(list = ls())
devtools::load_all(".", reset = TRUE)

# create log file
# TODO: figure out where this should be
log_initialise("./devtesting/testoutput")

# test dataset
testfile <- "./devtesting/testdata/abx2014.csv"
# specify column types
testfile_fieldtypes <- fieldtypes(PrescriptionID = ft_ignore()
																	,TimepointDate = ft_timepoint()
																	,PrescriptionDate = ft_ignore()
																	,PrescriptionType = ft_categorical()
																	,AdmissionDate = ft_datetime()
																	,Drug = ft_categorical()
																	,Formulation = ft_freetext()
																	,Dose = ft_number()
																	,DoseUnit = ft_categorical()
																	,FirstAdministrationDateTime = ft_datetime()
																	,Clusterid = ft_uniqueidentifier()
																	,AntibioticsSource = ft_categorical(aggregate_by_each_category=TRUE))

testfile <- "./devtesting/testdata/abx_IORD2018.csv"
# specify column types
testfile_fieldtypes <- fieldtypes(PrescriptionID = ft_ignore()
																							,PrescriptionDate = ft_timepoint()
																							,PrescriptionStatus = ft_ignore()
																							,PrescriptionType = ft_categorical(aggregate_by_each_category = TRUE)
																							,AdmissionDate = ft_datetime()
																							,Prescriber = ft_categorical()
																							,Drug = ft_categorical()
																							,Formulation = ft_freetext()
																							,Dose = ft_number()
																							,DoseUnit = ft_ignore()
																							,Frequency = ft_ignore()
																							,Route = ft_ignore()
																							,Indication = ft_ignore()
																							,ScheduledStartDateTime = ft_ignore()
																							,ScheduledStopDateTime = ft_ignore()
																							,DurationEnteredByPrescriber = ft_ignore()
																							,ReviewDateTime = ft_ignore()
																							,FirstAdministrationDateTime = ft_ignore()
																							,LastAdministrationDateTime = ft_ignore()
																							,NumberOfDosesAdministered = ft_ignore()
																							,SpecialInstructions = ft_ignore()
																							,TreatmentFunctionCode = ft_ignore()
																							,TreatmentSpecialty = ft_ignore()
																							,ConsultantName = ft_ignore()
																							,PatientOrderLocation = ft_ignore()
																							,Weight = ft_ignore()
																							,idsetuid = ft_ignore()
																							,Clusterid = ft_uniqueidentifier()
																							,LinkedNHSNumber = ft_ignore()
																							,LinkedORHNumber = ft_ignore()
																							,LinkedSurname = ft_ignore()
																							,LinkedForename = ft_ignore()
																							,LinkedSex = ft_ignore()
																							,LinkedBirthdate = ft_ignore()
																							,LinkedDeathdate = ft_ignore()
																							,SourceNHSNumber = ft_ignore()
																							,SourceORHNumber = ft_ignore()
																							,SourceSurname = ft_ignore()
																							,SourceForename = ft_ignore()
																							,SourceSex = ft_ignore()
																							,SourceBirthdate = ft_ignore()
																							,SourceDeathdate = ft_ignore()
																							,SpineCheckDate = ft_ignore()
																							,LinkageWarningFlag = ft_ignore()
																							,LinkageResult = ft_ignore()
																							,AntibioticsSource = ft_partition())

testcpdsourcedata <- load_dataset(testfile, fieldtypes = testfile_fieldtypes, na=c("","NULL"), showprogress=TRUE, log_directory = "./devtesting/testoutput/")

testcpdsourcedata <- load_dataset(source_df, fieldtypes = testfile_fieldtypes, na=c("","NULL"))
testcpdsourcedata <- load_dataset(clean_df, fieldtypes = fieldtypes(PrescriptionID = ft_uniqueidentifier()
																																		,TimepointDate = ft_timepoint()
																																		,PrescriptionDate = ft_datetime()
																																		,PrescriptionType = ft_categorical()
																																		,AdmissionDate = ft_datetime()
																																		,Drug = ft_categorical()
																																		,Formulation = ft_freetext()
																																		,Dose = ft_number()
#																																		,DoseUnit = ft_ignore()
																																		,FirstAdministrationDateTime = ft_datetime()
																																		,Clusterid = ft_uniqueidentifier()
																																		,AntibioticsSource = ft_partition()), na=c("","NULL"))


testcpdsourcedata <- load_dataset("./devtesting/testdata/abx_IORD2018.csv", fieldtypes(PrescriptionID = ft_uniqueidentifier()
																																							,PrescriptionDate = ft_timepoint()
																																							,PrescriptionStatus = ft_categorical()
																																							,PrescriptionType = ft_categorical(aggregate_by_each_category = TRUE)
																																							,AdmissionDate = ft_datetime()
																																							,Prescriber = ft_categorical()
																																							,Drug = ft_categorical()
																																							,Formulation = ft_freetext()
																																							,Dose = ft_number()
																																							,DoseUnit = ft_categorical()
																																							,Frequency = ft_categorical()
																																							,Route = ft_categorical()
																																							,Indication = ft_freetext()
																																							,ScheduledStartDateTime = ft_datetime()
																																							,ScheduledStopDateTime = ft_datetime()
																																							,DurationEnteredByPrescriber = ft_categorical()
																																							,ReviewDateTime = ft_datetime()
																																							,FirstAdministrationDateTime = ft_datetime()
																																							,LastAdministrationDateTime = ft_datetime()
																																							,NumberOfDosesAdministered = ft_number()
																																							,SpecialInstructions = ft_ignore()
																																							,TreatmentFunctionCode = ft_categorical()
																																							,TreatmentSpecialty = ft_categorical()
																																							,ConsultantName = ft_categorical()
																																							,PatientOrderLocation = ft_categorical()
																																							,Weight = ft_number()
																																							,idsetuid = ft_uniqueidentifier()
																																							,Clusterid = ft_uniqueidentifier()
																																							,LinkedNHSNumber = ft_uniqueidentifier()
																																							,LinkedORHNumber = ft_uniqueidentifier()
																																							,LinkedSurname = ft_freetext()
																																							,LinkedForename = ft_freetext()
																																							,LinkedSex = ft_categorical()
																																							,LinkedBirthdate = ft_datetime()
																																							,LinkedDeathdate = ft_datetime()
																																							,SourceNHSNumber = ft_uniqueidentifier()
																																							,SourceORHNumber = ft_uniqueidentifier()
																																							,SourceSurname = ft_freetext()
																																							,SourceForename = ft_freetext()
																																							,SourceSex = ft_categorical()
																																							,SourceBirthdate = ft_datetime()
																																							,SourceDeathdate = ft_datetime()
																																							,SpineCheckDate = ft_datetime()
																																							,LinkageWarningFlag = ft_categorical()
																																							,LinkageResult = ft_categorical()
																																							,AntibioticsSource = ft_partition())
																	, na=c("","NULL"), showprogress=TRUE, log_directory = "./devtesting/testoutput/")


testcpdsourcedata <- load_dataset("./devtesting/testdata/abx_IORD2018.csv", fieldtypes(PrescriptionID = ft_ignore()
																																													,PrescriptionDate = ft_timepoint()
																																													,PrescriptionStatus = ft_ignore()
																																													,PrescriptionType = ft_categorical(aggregate_by_each_category = TRUE)
																																													,AdmissionDate = ft_datetime()
																																													,Prescriber = ft_categorical()
																																													,Drug = ft_categorical()
																																													,Formulation = ft_freetext()
																																													,Dose = ft_number()
																																													,DoseUnit = ft_ignore()
																																													,Frequency = ft_ignore()
																																													,Route = ft_ignore()
																																													,Indication = ft_ignore()
																																													,ScheduledStartDateTime = ft_ignore()
																																													,ScheduledStopDateTime = ft_ignore()
																																													,DurationEnteredByPrescriber = ft_ignore()
																																													,ReviewDateTime = ft_ignore()
																																													,FirstAdministrationDateTime = ft_ignore()
																																													,LastAdministrationDateTime = ft_ignore()
																																													,NumberOfDosesAdministered = ft_ignore()
																																													,SpecialInstructions = ft_ignore()
																																													,TreatmentFunctionCode = ft_ignore()
																																													,TreatmentSpecialty = ft_ignore()
																																													,ConsultantName = ft_ignore()
																																													,PatientOrderLocation = ft_ignore()
																																													,Weight = ft_ignore()
																																													,idsetuid = ft_ignore()
																																													,Clusterid = ft_uniqueidentifier()
																																													,LinkedNHSNumber = ft_ignore()
																																													,LinkedORHNumber = ft_ignore()
																																													,LinkedSurname = ft_ignore()
																																													,LinkedForename = ft_ignore()
																																													,LinkedSex = ft_ignore()
																																													,LinkedBirthdate = ft_ignore()
																																													,LinkedDeathdate = ft_ignore()
																																													,SourceNHSNumber = ft_ignore()
																																													,SourceORHNumber = ft_ignore()
																																													,SourceSurname = ft_ignore()
																																													,SourceForename = ft_ignore()
																																													,SourceSex = ft_ignore()
																																													,SourceBirthdate = ft_ignore()
																																													,SourceDeathdate = ft_ignore()
																																													,SpineCheckDate = ft_ignore()
																																													,LinkageWarningFlag = ft_ignore()
																																													,LinkageResult = ft_ignore()
																																													,AntibioticsSource = ft_partition())
																	, na=c("","NULL")
																	, showprogress = TRUE
																	, log_directory = "./devtesting/testoutput/")


testcpdsourcedata2014 <- load_dataset("./devtesting/testdata/abx2014.csv", fieldtypes = fieldtypes(PrescriptionID = ft_ignore()
																																		,TimepointDate = ft_timepoint()
																																		,PrescriptionDate = ft_ignore()
																																		,PrescriptionType = ft_ignore()
																																		,AdmissionDate = ft_datetime()
																																		,Drug = ft_ignore()
																																		,Formulation = ft_ignore()
																																		,Dose = ft_number()
																																		,DoseUnit = ft_categorical()
																																		,FirstAdministrationDateTime = ft_datetime()
																																		,Clusterid = ft_ignore()
																																		,AntibioticsSource = ft_partition()), na=c("","NULL")
																			, log_directory = "./devtesting/testoutput/")

#print(testcpdsourcedata)

testcpddata2014_byweek <- aggregate_data(testcpdsourcedata2014, aggregation_timeunit = "week", changepointmethods = "all", showprogress = TRUE)


testcpddata_byday <- aggregate_data(testcpdsourcedata, changepointmethods = "none", showprogress = TRUE)
testcpddata_bymonth <- aggregate_data(testcpdsourcedata, aggregation_timeunit = "month", changepointmethods = "none", showprogress = TRUE)
testcpddata_byweek <- aggregate_data(testcpdsourcedata, aggregation_timeunit = "week", changepointmethods = "none", showprogress = TRUE)
testcpddata_byquarter <- aggregate_data(testcpdsourcedata, aggregation_timeunit = "quarter", changepointmethods = "none", showprogress = TRUE)
testcpddata_byyear <- aggregate_data(testcpdsourcedata, aggregation_timeunit = "year", changepointmethods = "none", showprogress = TRUE)

summarise_aggregated_data(testcpddata_byday)
print(testcpddata_byyear)
export_aggregated_data(testcpddata_byday, save_directory = "./devtesting/testoutput/")


plot_aggregatefield_byaggtype(aggfield = testcpddata_byday[["subaggregates"]][["AntibioticsSource"]][["ITU"]][["aggregatefields"]]$AdmissionDate,aggtype = "missing_n", changepoint_methods = "none", save_plot = FALSE)

plot_aggregatefield_byaggtype(aggfield = testcpddata_byday$subaggregates[[1]][[2]]$aggregatefields$PrescriptionType,aggtype = "distinct", save_plot = FALSE)


plot_aggregated_data(testcpddata_byday, save_plot = TRUE, save_directory = "./devtesting/testoutput/", save_filetype = "png", showprogress = TRUE)

plot_changepoint_summary(testcpddata_byday, save_plot = TRUE, save_directory = "./devtesting/testoutput", save_filename = "Changepoint_summary_abx_IORD2018", save_filetype = "png", showprogress = TRUE)
plot_changepoint_summary(testcpddata_byday, save_plot = FALSE, save_directory = "./devtesting/testoutput/", save_filetype = "png", showprogress = TRUE)
#plot_changepoint_summary(testcpddata_byday, changepoint_methods = "-is_na", save_plot = TRUE, save_directory = "../devtesting/testoutput/", save_filetype = "png", save_filename = "Changepoint_summary_-isna", showprogress = TRUE)
plot_changepoint_summary(testcpddata_byday$subaggregates[[1]][[1]], save_plot = TRUE, save_directory = "./devtesting/testoutput/", save_filetype = "png", showprogress = TRUE)
plot_changepoint_summary(testcpddata_byday$subaggregates[[1]][[2]], save_plot = TRUE, save_directory = "./devtesting/testoutput/", save_filetype = "png", showprogress = TRUE)

summarise_aggregated_data(testcpddata_byday)



generate_report(sourcedata = testcpdsourcedata2014, aggregatedata = testcpddata2014_byweek, save_directory = "./devtesting/testoutput")

generate_report(sourcedata = testcpdsourcedata,
								aggregatedata = aggregate_data(testcpdsourcedata, aggregation_timeunit = "week", changepointmethods = "none", showprogress = TRUE),
								save_directory = "./devtesting/testoutput")

rmarkdown::render(input = "./R/report_htmldoc.Rmd"
									, output_dir = "./devtesting/testoutput"
									, params = list(sourcedata = testcpdsourcedata, aggregatedata = testcpddata_byday))


